# Generated by Django 5.0.4 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproTracker_app', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conscience',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('connaissance', models.CharField(max_length=45, null=True)),
                ('mot_cle_connaissance', models.CharField(max_length=100, null=True)),
                ('utilisation', models.CharField(max_length=45, null=True)),
                ('mot_cle_utilisation', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'conscience',
            },
        ),
        migrations.AlterModelTable(
            name='personne',
            table='personne',
        ),
    ]
