# Generated by Django 5.0.4 on 2024-04-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproTracker_app', '0003_conscience_alter_personne_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('doctorant', models.CharField(max_length=100)),
                ('annee_realisation', models.IntegerField()),
                ('enquete', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enquete',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='General',
        ),
    ]
