# Generated by Django 5.0.4 on 2024-05-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reproTracker_app', '0005_doctorant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorant',
            options={'managed': False},
        ),
    ]
