# Generated by Django 5.0.4 on 2024-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproTracker_app', '0006_alter_doctorant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generale',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('docteur', models.CharField(max_length=45, null=True)),
                ('ann_realise', models.DateField(blank=True, null=True)),
                ('id_enq', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'generale',
            },
        ),
        migrations.AlterModelTable(
            name='doctorant',
            table='doctorant',
        ),
    ]
